### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by tsenart** [pascaldekloe/wordpack#1]
Hello! 

I'm playing around with this package. I have a few questions.

1. Does `pack32` not offer a decoder? Only encoder? Very excited for the perf numbers here. What would it take to have vectorization for pack64 as well?
2. It would be helpful to write an example of the right way to encode and decode variable length lists of integers. I assume I need to chop them up in blocks of 64, and if the last page doesn't align, it can't be encoded? Or should it be padded with zeroes?
3. If the offset isn't fixed across different 64 int blocks, as the Godocs suggest (i.e. use src[0]), then in a serialized encoding we'd have to store the offset for each block for proper decoding. Is the idea here to instead just use a fixed frame of reference offset for the whole list of integers?

Thank you!

**Comment by pascaldekloe** [comment]
Hey Tomás.

1. Only `pack64` and its code generater made it into a stable release. The pending PoC in `pack32` is incomplete. SIMD did OK. Go's assembly not so much. 😄 I tried some more directly with clang(1) and got distracted. Will definitely continue one day. Per 32 turned out to be more efficient with SIMD. Can't remember exactly why. It might have something to do with the overall space in vector registers. A total of 32 64-bit values will fit nicely in ARM's 32 128-bit registers, with room left for calculation.

2. https://pkg.go.dev/github.com/pascaldekloe/wordpack@v1.0.1/pack64#example-package-Codec The last value could be repeated as padding to help compression a bit. 😉

3. The ideal offset is one close to the actual values. You may want to fix one close to a common value in some cases. Perhaps continue with the last one from the previous batch? Or maybe a running average?

The API definitely could use a streaming codec which frames the offset and padding somehow. Patches are welcome.

**Comment by pascaldekloe** [comment]
I've put the assembly in a gist in case you're interested...

https://gist.github.com/pascaldekloe/1d3e5e407dffb781fc2a31e2033441ea

**Comment by tsenart** [comment]
Thanks for the swift response! I'd be glad to contribute a patch once I understand how to use this properly :)

I had seen the example you linked, but that still leaves some open questions for me. I assume that the compression ratio per block is variable, which results in a variable length of words for each block in a list of blocks?

Assume I have 1M integers to encode over the wire, and then decode in another process. The encoding part would look something like this:

```go
packed := make([]pack64.Word, 0, len(data)/2) // Optimistic sizing
for i := 0; i < len(data) && len(data) >= 64; i += 64 {
	packed = pack64.AppendDeltaEncode(packed, (*[64]int64)(data[:64]), data[0])
	data = data[64:]
}

// Last page didn't align to 64, leave uncompressed
for len(data) > 0 {
	packed = append(packed, pack64.Word(data[0]))
        data = data[1:]
}

// Write number of packed words
if err := w.WriteUint32(uint32(len(packed))); err != nil {
	return err
}

if _, err := pack64.Write(wrt, packed); err != nil {
	return err
}
```

The issue I have is that on the other side, for decoding, I don't know the length of packed per block, only the total length of all packed blocks in one long word slice. As far as I understand, I'd have to serialize the length of each packed block together with it in order to decode it properly. Is that correct? Do you see a way around it?

```go
sz, err := mr.ReadUint32()
if err != nil {
	return nil, err
}

packed := make([]pack64.Word, 0, sz)
if _, err := pack64.ReadFull(mr, packed); err != nil {
	return nil, err
}

for len(packed) >= 0 {
	data = pack64.AppendDeltaDecode(data, packed, data[len(data)-1])
	packed = packed[64:]
}

// TODO: Handle last page
```

**Comment by pascaldekloe** [comment]
Exactly @tsenart. You need to make a frame which packs the initial offset plus the size. Compression ranges from 100% (when all values match the offset) to 0 %, thus 0 to 64 bits times 64 per pack. I think it is important to think about memory alignment when designing the header. Append works best on multiples of 8 bytes, ideally 16.

**Comment by tsenart** [comment]
@pascaldekloe: Gonna give it a try, but having to pack an extra full int (i.e. offset) per 64 ints plus a uint8 for size per frame will eat into the compression gains. I guess there's no way around it though.

**Comment by pascaldekloe** [comment]
The offset is only needed once for the first pack. Any following pack can use the last value from the previous pack as their offset. You could also fix the initial offset to `0`, or make it a stream parameter for the user to decide.

We need 7 bits to encode size range 0..64, and we need 6 bits to encode the actual integer count 1..64. Since padding only applies to the last pack, we could describe 9 pack-sizes in one `pack64.Word` with one bit to spare for a "full" flag. The final frame has `full` false (`0`), and it encodes the size in 6 bits, range 1..64, with size 0 padded as 0x0000 0000 0000 0000 (equivalent to the zero string), which leaves us 9 bits to count the number of integers in the last frame. 😉

```go
offset := in[0]

// start output stream with offset value
buf := append(make([]Word, 0, 9 * 64 + 1), offset)

// write full batches
for (len(in) >= 9 * 64) {
        var header Word = 1 << 63 // full flag
        headerIndex := len(words)
        words = append(words, 0) // reserve location

        n := len(buf)
        buf = pack64.AppendDeltaEncode(buf, (*[64]int64)(in[0*64:1*64]), offset)
        header = len(buf) - n // size of first pack

        n = len(buf)
        buf = pack64.AppendDeltaEncode(buf, (*[64]int64)(in[1*64:2*64]), in[1*64-1])
        header |= (len(buf) - n) << 7

        …

        n = len(buf)
        buf = pack64.AppendDeltaEncode(buf, (*[64]int64)(in[8*64:9*64]), in[8*64-1])
        header |= (len(buf) - n) << 56

        // pass input
        offset = in[9*64-1]
        in = in[9*64]

        // write batch with header
        words[headerIndex] = header
        if err := out.WriteWords(buf); err != nil {
                return err
        }

        buf = buf[:0]
}

header := len(in) << 56 // last frame count
buf = append(buf, 0) // reserve location

sizeShift = 0
for (len(in) > 63) {
        n = len(buf)
        buf = pack64.AppendDeltaEncode(buf, (*[64]int64)(in[:64]), offset)
        size := len(buf) - n
        if size == 0 {
                // most optimal case replaced by its
                // equivalent in second-most optimal
                buf = append(buf, 0)
        } else {
                size-- // saves 1 bit of address space
        }
        header |= size << sizeShift
        sizeShift += 6
}
buf[0] = header

return out.WriteWords(buf)
```

**Comment by pascaldekloe** [comment]
Does that make any sense @tsenart? I forgot the final `if len(in) != 0` with padding b.t.w.. 🙃

**Comment by tsenart** [comment]
Hey! Yep, that makes sense, thank you for expanding.

I'm running a bunch of experiments for our use case. I was hoping that pure integer compression such as the one provided by this package would bring us close enough to the compression ratio that zstd is giving us. So far, it's really far apart – 3MB vs 20MB.

I'm trying to make deserialization of this data faster than it currently is, but we can't afford loosing that much on compression.

Using this package together with zstd seems to harm zstd's ability to compress well also. It does best with just writing out the integers without any additional compression before.

**Comment by pascaldekloe** [comment]
Delta compression is no match for the more clever algorithms out there., although it can work wonders in some edge cases, and it can get close to the memory bandwidth, like no 'z' algorithm will.

**Comment by pascaldekloe** [comment]
Streams realized with near-zero overhead.

```
BenchmarkDeltaBitEncoding/63BitDelta/uint64/Encode-8       	19251207	        62.11 ns/op	8243.81 MB/s	         0.8364 Gℕ/s
BenchmarkDeltaBitEncoding/63BitDelta/uint64/Decode-8       	25869920	        46.19 ns/op	11083.95 MB/s	         0.8368 Gℕ/s
BenchmarkWritePack-8                                       	26757070	        44.67 ns/op	11462.06 MB/s	         0.8367 Gℕ/s
BenchmarkReadAppend-8                                      	27144919	        44.12 ns/op	11605.74 MB/s	         0.8351 Gℕ/s
```
